### PR TITLE
easy to easier

### PR DESCRIPTION
**Pull request by ascott1**
This changes some instances of "easy" to "easier" to prevent assumptions that we are somehow simplifying the regulation text itself.

### CODE REVIEW

**Comment by KimberlyMunoz** [comment]
The about page has a header that says "Easy to Read" should that be changed to "Easier to Read"?

**Comment by ascott1** [comment]
I think that's changed [here](https://github.com/cfpb/regulations-site/pull/708/files#diff-fbe06dee92de24292370270adfa2c7e0R39).

**Comment by khandelwal** [comment]
This looks good.

**Comment by ascott1** [comment]
Thanks @khandelwal

**Comment by KimberlyMunoz** [comment]
:boat:

**Comment by ascott1** [comment]
:fishing_pole_and_fish:

**Pull request merged**
