### PR TITLE
add hover states for sidebar expandables and fix #777

### LINKED ISSUE #777: Back navigation from footnotes is off by a few lines
For example, see http://www.consumerfinance.gov/eregulations/sxs/1026-1-c/2013-28210?from_version=2015-18239. Click on footnote "160" to navigate to the footnote text. Clicking now on the "return" link does not take you back to where you came from. It's off by 2-3 lines.

### PR DESCRIPTION
**Pull request by ascott1**
Non hovered state:

screen shot 2016-02-11 at 11 42 28 am

On hover:

screen shot 2016-02-11 at 11 42 24 am

screen shot 2016-02-11 at 11 42 15 am

## Review
@willbarton

### CODE REVIEW

**Comment by jehlers** [comment]
:smile:

**Comment by ascott1** [comment]
This also adds a fix for #777 by making the direct linked SxS header act the same as the navigated to SxS analysis.

**Comment by willbarton** [comment]
My finger was on the merge button.

**Comment by ascott1** [comment]
Whoops. I thought it had been merged already.

**Comment by willbarton** [comment]
This fixes #777 for me locally.

**Comment by willbarton** [comment]
a3cf9df634ecd949f5ed61f03a6bc57a

**Pull request merged**
