### PR TITLE
ID tags for testing

### PR DESCRIPTION
**Pull request by ascott1**
This adds some additional ID tags to the TOC to simplify selecting elements for testing.

@willbarton @KimberlyMunoz @grapesmoker

### CODE REVIEW

**Comment by OrlandoSoto** [comment]
:+1:

**Comment by KimberlyMunoz** [comment]
Looks good, although maybe we'd like to put in [`qa-` classes ](http://csswizardry.com/2015/03/more-transparent-ui-code-with-namespaces/) instead as a pattern to make it more obvious not to remove or re-name these tags in the future.

**Comment by ascott1** [comment]
> Looks good, although maybe we'd like to put in qa- classes instead as a pattern to make it more obvious not to remove or re-name these tags in the future.

Hmm, that's a clever idea.

**Comment by ascott1** [comment]
@KimberlyMunoz do you mind merging? I really like the `qa-` idea, but I vote for leaving it as is for now since that isn't done by any of our other repos.

**Comment by KimberlyMunoz** [comment]
Of course!

**Comment by ascott1** [comment]
Thank you!

**Pull request merged**
