### PR TITLE
add cell borders

### PR DESCRIPTION
**Pull request by ascott1**
This adds borders around the table cells to make the tables in the tool be closer in appearance to the originals.

screen shot 2015-04-10 at 4 21 52 pm

### CODE REVIEW

**Comment by khandelwal** [comment]
:+1:

**Comment by khandelwal** [comment]
Where are my merge rights?

**Comment by Scotchester** [comment]
You left them in your cube at Constitution Square.

**Comment by Scotchester** [comment]
:trollface:

**Comment by jehlers** [comment]
Tabels!!!! :tada:

**Comment by DarthDippy** [comment]
gg

**Pull request merged**
