### PR TITLE
Refactor drawer state

### PR DESCRIPTION
**Pull request by ascott1**
This refactor's the drawer state in the following ways:

- No longer relies on the confusing and generic `active` class
- Keeps the drawer state out of the DOM
- Drawer remains open or closed when resizing the browser window (a :gift: for @khandelwal)
- Removes redundant small screen specific css
- Removes the janky animation

@KimberlyMunoz can you review and test?

### CODE REVIEW

**Comment by KimberlyMunoz** [comment]
:+1: 

While I was keyboard testing the last pull request, I noticed that there was a bug while navigating between search/timeline/toc and the refactoring here unintentionally fixed it! :clap:

**Comment by KimberlyMunoz** [comment]
Although sadly, this doesn't fix the [outstanding bug on Android ICS using the stock browser](https://cloud.githubusercontent.com/assets/1860176/7949270/46a1d64c-095a-11e5-9619-f7ac5ac6e94b.png).

**Comment by ascott1** [comment]
> Although sadly, this doesn't fix the outstanding bug on Android ICS using the stock browser.

Argh, I was really hoping it would fix that. Silly `position: fixed`

**Comment by KimberlyMunoz** [comment]
Yeah. I merged anyway since it was an existing issue.

**Pull request merged**
