### PR TITLE
Remove Bower dependency

### PR DESCRIPTION
**Pull request by ascott1**
This moves us to completely using `npm` to manage packages on the front-end.

To test:

1. Clone my branch locally and run the `frontendbuild.sh` script. This will run `npm install` and the `grunt build` command. The site should build with no errors.
2. Start the server and ensure that there are no console.log errors reporting unfound scripts.

## Review

@willbarton

### CODE REVIEW

**Comment by willbarton** [comment]
giphy-5

**Comment by willbarton** [comment]
Did you mean to commit `regulations/static/regulations/js/built/lib/respond/respond.min.js`?

**Comment by cmc333333** [comment]
Ugh. We should have sent this up: https://github.com/18F/regulations-site/pull/62

Highlights relevant for you:
* README changes
* unveil for images needed to be replaced as it was being pulled in from bower

**Comment by ascott1** [comment]
> Ugh. We should have sent this up: 18F#62

Double ugh.

- README changes coming. 
- I had long ago replaced Unveil with my own version with the same API, which allowed us to write unit tests for the JS views.

> Did you mean to commit regulations/static/regulations/js/built/lib/respond/respond.min.js?

@willbarton nope. fix coming.

**Comment by ascott1** [comment]
This should be all set, unless @cmc333333 would rather PR the 18F changes (which I'm also ok with)

**Comment by willbarton** [comment]
stimpy-red-button

**Pull request merged**
