### PR TITLE
Grunt updates

### PR DESCRIPTION
**Pull request by ascott1**
This should make working with the front-end more nicerer.

## Additions
 
- Enables livereload in development environments
- Adds the browserify task to watch and splits it from the LESS task for maximum speediness
 
## Changes
 
- Updates the LESS task to include sourcemaps and use the non-minified version of the the less file in development
-  Ignore the regulations-core directory for the times we use the dummy_api in testing

## Review
 
- @KimberlyMunoz

### CODE REVIEW

**Comment by KimberlyMunoz** [comment]
:+1: :+1:

I had some concerns about excluding the css map, but the site works great without it and this definitely makes working on the front-end more pleasant. The only thing is that when I run `grunt build` now, there's a few files that change from the current version, which seems odd if our gruntfiles are the same.

image

**Comment by ascott1** [comment]
Hmm, it's possible that we have slightly different dependencies locally, since some of them are not pinned to an exact version number. I'll do some digging...

**Comment by ascott1** [comment]
Oh, and once we have a proper build script on the server we should remove these built files from source control.

**Comment by ascott1** [comment]
Looks like this is related to sourcemaps on the JS files in development mode... I'm not sure that there's a fix until we stop checking these in, but I'm open to any ideas.

screen shot 2015-03-02 at 10 53 46 am

**Comment by ascott1** [comment]
Thanks @KimberlyMunoz!

**Pull request merged**
