### PR TITLE
add npmrc file to pin newly installed dependencies

### PR DESCRIPTION
**Pull request by ascott1**
Now when running `npm install --save-dev NEWDEPENDENCY` that dependency will be pinned to the specific version installed, rather than allowing users download the latest minor release.

### CODE REVIEW

**Comment by willbarton** [comment]
rashida-jones-the-office-shrug-gif

--

Is the process of managing dependency versions going to be documented somewhere, if someone comes to the project and needs to update a dependency, change a dependency, add a dependency, etc?

**Comment by ascott1** [comment]
> Is the process of managing dependency versions going to be documented somewhere, if someone comes to the project and needs to update a dependency, change a dependency, add a dependency, etc?

Yes, but I think it will live outside of the project itself in the front-end standards (or somewhere similar). Here's my current draft:

https://gist.github.com/ascott1/f8696e13453fa0c9f1a84b65b0033f09

**Comment by willbarton** [comment]
Excellent. Is this ready to merge?

**Comment by ascott1** [comment]
Yessir. Merge away.

**Pull request merged**
