### PR TITLE
Fix definition loading indicator, addresses #736

### PR DESCRIPTION
**Pull request by ascott1**
Though I personally love the spinning text effect, I suspect that our users may not appreciate it. This fixes that.

## Review

@willbarton

### CODE REVIEW

**Comment by khandelwal** [comment]
Spinning text is a FEATURE. I'm hoping you don't merge this.

**Comment by ascott1** [comment]
@willbarton hold off on merging this... another commit is coming.

**Comment by willbarton** [comment]
@khandelwal I'll let you guys work on making reading regs exciting. We'll keep the text boring and stationary on our side.

selfie-1

**Comment by ascott1** [comment]
@willbarton is just showing off his gif skills now.

**Comment by willbarton** [comment]
But I got the direction of rotation backwards 😞

**Pull request merged**
