### PR TITLE
Add loading indicator for Section by Section analysis, closes #725

### LINKED ISSUE #725: Add a loading indicator for Section by Section analysis
See: <https://github.com/cfpb/regulations-site/pull/722#issuecomment-109391957>

> The first time I grab a new SxS analysis, I get a blank white screen for a few ms which is a little noticeable. It only happens sometimes the first time I grab a new SxS and it isn't consistent, so I'll just file an issue for something later.

Let's add a loading indicator to give the user some visual feedback when this occurs.

### PR DESCRIPTION
**Pull request by ascott1**
#722 changed the way the SxS breakaway view is loaded to animate before the content is loaded. That means that when content is loaded slowly, the user stares at a semi-blank screen while waiting for the request to finish. This adds a little spinning indicator in those scenarios.

spinning

It's not beautiful, but it's rare that this appears and is a definite UX win.

## Review

@KimberlyMunoz do you mind doing the honors?

### CODE REVIEW

**Comment by willbarton** [comment]
I keep watching the gif waiting for something to load.




(I think that means it works as intended.)

**Comment by KimberlyMunoz** [comment]
I'm getting an error compiling the LESS since mixins.less is called before cf-icons.less. Changing the order in main.less should fix it.

**Comment by ascott1** [comment]
> I'm getting an error compiling the LESS since mixins.less is called before cf-icons.less. Changing the order in main.less should fix it.

Oh, whoops! Thanks for catching this. Not sure why I didn't get the error locally.

**Comment by ascott1** [comment]
Updated and pushed

**Pull request merged**
