### PR TITLE
Add long-term caching

### PR DESCRIPTION
**Pull request by cmc333333**
Many of our pages take a second or more to load, yet change very rarely. Add an eregs-specific cache which will store these pages for 15 days. Default to a file-system solution so we can easily clear it when new data is present.

On a pre-caching script which loads several hundred pages, this cache caused a 40x speedup.

### CODE REVIEW

**Comment by rosskarchner** [comment]
We are now using this in production!

I'm kind of bummed that the page cache isn't shared between servers (so every URL is theoretically generated *twice*), but we're still thinking through that. Basically: is the increased efficiency of cache usage worth the overhead of a network mount or some other solution?

**Comment by ascott1** [comment]
Whoa, eRegs *screeeeaaaaaammmmssss* now. Amazing.

**Comment by khandelwal** [comment]
Yeah, the speed improvements are AWESOME.

**Comment by ascott1** [comment]
I'm just clicking ALL THE THINGS.

**Comment by khandelwal** [comment]
CLICK, CLICK, CLICK.

**Comment by cmc333333** [comment]
Yay caching. A goal I've had for a long time is to make a static site generator for this, and the content, by definition, almost never changes. The long-term cache is a middle ground -- no significant rework of the underlying system, yet massive performance boost.

@rosskarchner - if you wanted to share across servers, memcached is probably the answer. The only tricky bit would be to verify timeouts. Luckily, you can configure that all without changing the eregs code base :)

**Comment by rosskarchner** [comment]
Things may have gotten a bit faster (or I'm imagining things), as these servers are now using SSD's

**Comment by cmc333333** [comment]
@ascott1 I revise: 

For development, you probably want:

```python
    'eregs_longterm_cache': {
        'BACKEND': 'django.core.cache.backends.dummy.DummyCache',
        'TIMEOUT': 60*60*24*15,     # 15 days
    },
```

**Pull request merged**
