### PR TITLE
Begin Less refactor

### PR DESCRIPTION
**Pull request by ascott1**
This does a few things:

- Switches to using grunt-contrib-cssmin for minifying css, which resulted in 20kb+ of savings
- Removes all of the weird media query specific files so that media queries are easier to track down
- Refactors the layout.less in the direction of things being mobile first

## Review

@KimberlyMunoz

### CODE REVIEW

**Comment by ascott1** [comment]
@KimberlyMunoz I moved a lot around here. Would you mind giving this a thorough look through when you get a chance? I'm hoping this makes the layout easier to grok, but please feel free to make recommendations.

**Comment by KimberlyMunoz** [comment]
Looking at this today!

**Comment by ascott1** [comment]
Thanks!

**Comment by KimberlyMunoz** [comment]
:+1:

Big fan of the work done on layout.less

giphy

**Comment by ascott1** [comment]
> Big fan of the work done on layout.less

Shucks, thank you. Hopefully it'll be a teeny bit easier to figure out what's going on in that file now.

**Pull request merged**
