### PR TITLE
Replace Require.js with Browserify

### PR DESCRIPTION
**Pull request by ascott1**
This does a lot of foundational cleanup of the JS app and replaces require.js with browserify. This change should make the application easier to maintain and will give us a lot more flexibility going forward.

## Benefits

- A single http request reducin' .js bundle
- Simpler CommonJS syntax
- In line with other CFPB apps (Owning a Home)
- We can now use npm goodness

### CODE REVIEW

**Comment by ascott1** [comment]
Sorry @cmc333333 

screen shot 2015-02-24 at 4 20 19 pm

**Comment by contolini** [comment]
truegif

**Comment by theresaanna** [comment]
@ascott1 is teh magics.

Again, I'm sorry. THINGS CHANGE QUICKLY, OK!?

**Comment by contolini** [comment]
@theresaanna :heart: 

@ascott1 This is going to take me a bit to review but I'm all over it.

**Comment by ascott1** [comment]
> Again, I'm sorry. THINGS CHANGE QUICKLY, OK!?

NO REGRETS

**Comment by theresaanna** [comment]
See, I'm not living the NO REGRETS life anymore. This is a problem.

**Pull request merged**
