### PR TITLE
use cfgov_setup for building frontend assets

### PR DESCRIPTION
**Pull request by rosskarchner**

### CODE REVIEW

**Comment by rosskarchner** [comment]
This actually fails right now:

```
Done, without errors.
✗ High severity vulnerability found on minimatch@0.2.14
- desc: Regular Expression Denial of Service
- info: https://snyk.io/vuln/npm:minimatch:20160620
- from: regulations-site@0.1.0 > chokidar@0.12.6 > readdirp@1.3.0 > minimatch@0.2.14
Upgrade direct dependency chokidar@0.12.6 to chokidar@1.1.0 (triggers upgrades to readdirp@2.0.1 > minimatch@3.0.2)

Tested 32 dependencies for known vulnerabilities, found 1 vulnerability, 1 vulnerable path.
```

**Comment by rosskarchner** [comment]
It's also worth celebrating that the old code probably wouldn't have caught this error, or at least failed later, because `call` doesn't care whether the command succeeds or fails:

https://github.com/cfpb/regulations-site/pull/817/files#diff-2eeaed663bd0d25b7e608891384b7298L23

**Comment by willbarton** [comment]
@rosskarchner Hmm, the failure in Travis looks different from that, it seems to be with fsevents.

**Comment by rosskarchner** [comment]
Either way, it cuts to the problem that started this whole thing: making sure the python build fails if the frontend build fails ;)

**Comment by willbarton** [comment]
@rosskarchner Looks like this should be fixed!

**Comment by rosskarchner** [comment]
Trying it now

**Comment by rosskarchner** [comment]
looks good!

**Pull request merged**
