### PR TITLE
Performance and accessibility tweaks

### PR DESCRIPTION
**Pull request by ascott1**
This does the following:

- Goes back to loading local font files instead of a font provider CDN (sorry @KimberlyMunoz :disappointed:)
- Adds appropriate ARIA roles
- Loads Modernizr inline in the `<head>` to remove the request (this is ugly but seems worthwhile since we need it on the initial page load)

## Notes

- I wanted to add `async` to our `script` tags but Google Tag Manager's reliance on jQuery meant that this broke analytics. I'm hoping to work with @mistergone to fix this as using `async` made page loads feel snappy
- I also tested using Filament Group's [loadCSS](https://github.com/filamentgroup/loadCSS), but the flash of unstyled content and some jankiness with scrolling led me to abandoning it for now

## Review

@KimberlyMunoz

### CODE REVIEW

**Comment by KimberlyMunoz** [comment]
:fallen_leaf: 

Reviewing this and your other pull request between meetings today.

**Comment by KimberlyMunoz** [comment]
## Fonts

Tested this in IE 9, IE 10, IE 11, Chrome, and Safari. Here's what it looks like in IE9, 10 and Safari.

image

The one thing I want to flag is that there seems to be a standard for how we're embedding fonts. I went off the [licensed-fonts.css](https://github.com/cfpb/generator-cf/blob/master/app/templates/src/static/css/licensed-fonts.css)* (which I didn't write, I just moved.) But what you're using seems to work, and uses the IE trick that most folks recommend. I would just change the font-weight lines in the `.avenir-demi/bold` mixins to fix in cases where the fonts don't load. 

## Performance 

### Old (upstream/master)

image

image


### New

image

image

*Tested using Justice.js and the test API. Testing on our internal API might be a better metric for what this will look like in the wild. Those numbers are a bit higher*

**Comment by ascott1** [comment]
> Tested using Justice.js and the test API. Testing on our internal API might be a better metric for what this will look like in the wild. Those numbers are a bit higher

This is really cool. I wasn't familiar with Justice.js until now. You're right that the numbers are misleading since it's running locally, but it's a neat way to see that we're own the right path on my quest to get us under 1000ms in production.

Thanks for testing it so well! Mind merging when you get a chance?

**Comment by ascott1** [comment]
> The one thing I want to flag is that there seems to be a standard for how we're embedding fonts. I went off the licensed-fonts.css* (which I didn't write, I just moved.) But what you're using seems to work, and uses the IE trick that most folks recommend. I would just change the font-weight lines in the .avenir-demi/bold mixins to fix in cases where the fonts don't load.

Just noticed this. I'll dig into this later today and update the PR as I'd like it to match the new standard.

**Comment by ascott1** [comment]
@KimberlyMunoz, I noticed that the CF [licensed fonts](https://github.com/cfpb/cf-typography/blob/gh-pages/src/licensed-fonts.css) file still points to the CDN. My  understanding is that we'll soon be moving away from the CDN.

I matched the font weights in the mixins to those in the @font-face rules. I *thought* there was a reason I did it the other way originally, but I couldn't find anything to back that up.

**Pull request merged**
