### PR TITLE
fix the non-rendering of paragraphs that only contain tables

### PR DESCRIPTION
**Pull request by grapesmoker**
Right now this only works for paragraphs that have a <title> tag preceding the content and the title starts with "table" but hopefully at some point once I figure out how these pieces work together I can come up with a generic solution.

### CODE REVIEW

**Comment by cmc333333** [comment]
Food for thought as an alternative strategy: we're removing all browser-rendered li markers and effectively moving the template-generated markers "out" (i.e. to the left) to match the appearance of browser paragraph markers. This means markerless paragraphs, paragraphs with _skipped_ markers, or crazy paragraph markers like "(b) - (d)" should all work out of the box.

We did something very similar at CFPB in the appendices section, but I messed that up pretty badly. @xtine has been fixing the concept up.

Should we send this your way when we finish?

**Comment by willbarton** [comment]
@cmc333333 it sounds like non-browser markers would be ideal for some other marker-related situations we have. If you could send it this way, that'd be grand!

**Comment by grapesmoker** [comment]
That would be great. I'm not sure if it would solve this particular issue though? The problem is in the rendering code which doesn't render the search and replace layer if there's no text, which means standalone tables don't get rendered.

**Comment by cmc333333** [comment]
@grapesmoker my bad! I saw the changes to `list_type` and became overly excited

**Comment by grapesmoker** [comment]
Oh, yeah, I was doing some monkeying with list_type but I've actually done away with it here because we've simplified the rendering logic some on the template end. Now that we have explicit markers, we just use those.

**Pull request merged**
