### PR TITLE
Add loading spinner icon class

### PR DESCRIPTION
**Pull request by ascott1**
- updates to the latest cf-icons files and less
- adds a loading spinner class (to be used with the fr notices on the landing page)

### CODE REVIEW

**Comment by ascott1** [comment]
@KimberlyMunoz do you mind reviewing this when you get a chance?

**Comment by KimberlyMunoz** [comment]
Looks good. 

Where is `.loading-spinner` going to be used? There's a few cases where I create it and it spins a little too much by rotating in a huge circle instead of in place, like say... if you replaced the right-icon with a loading spinner to fire it up really quick for a pull request. If it's only going to be used in one place and it works there, there probably isn't a reason to change it, but I found setting the height and width stops that issue from coming up.

~~~
.loading-spinner:after {
    .cf-icon;
    .cf-icon__spin;
    display: block;
    width: 1em;
    height: 1em;
    content: @cf-icon-update;
    color: @pacific;
    font-size: 1.375em;
    margin: 2em auto;
}
~~~

**Comment by ascott1** [comment]
Good suggestion. I added the height and width for future compatibility. It's going to be used on the fr-notices that are loaded on the landing page so that there's no longer a weird eye jolt as content just shows up there.

**Comment by KimberlyMunoz** [comment]
Cool. I'll merge when the Travis build finishes.

**Comment by ascott1** [comment]
WHOOHOO :repeat:

**Pull request merged**
