### PR TITLE
Patch dependencies and fail builds for known npm package vulnerabilities

### PR DESCRIPTION
**Pull request by ascott1**
This does two things:

1. Patches a few nested dependencies
2. Sets up the tool Synk to test our npm dependencies and fail builds and Travis if there are any known vulnerabilities

### CODE REVIEW

**Comment by ascott1** [comment]
One thing that might be annoying... the `./frontendbuild.sh` command will fail if there's a known vulnerability. This could be a good thing as it would force a person to fix that before moving on, but it could also be a frustration point. Thoughts?

**Comment by willbarton** [comment]
@ascott1 theoretically, with version pinning and shrinkwrapping, this is something that would be encountered when dealing with new versions, correct? Or would be dealt with upstream? This wouldn't be a regular occurrence for an end-user?

**Comment by ascott1** [comment]
@willbarton that's correct. It should be a very rare occurrence for any end-user.

**Comment by willbarton** [comment]
@ascott1 then I'd say the benefits seem to vastly outweigh the potential frustration. 

:+1:

**Pull request merged**
