### PR TITLE
updated README

### PR DESCRIPTION
**Pull request by grapesmoker**
Updated the README to remind people that they need to specify the locations of their static resources before starting the demo server.

### CODE REVIEW

**Comment by KimberlyMunoz** [comment]
Is this related to #698?

I thought that was about running a grunt build or grunt squish to get the minified JS and avoid the empty sidebar.

**Comment by grapesmoker** [comment]
Is that how you're supposed to do it? I'm not too well-versed in Grunt, obviously. I will say though that when I run grunt build I get a mile-high stacktrace, so that's how I got around that problem.

**Comment by grapesmoker** [comment]
I'm getting:

1) Non-DOM Helper functions: "before all" hook:
     ReferenceError: Set is not defined
(stacktrace follows)

2) Version Finder Helper Functions: "before all" hook:
     ReferenceError: Set is not defined
(stacktrace follows)

No coverage information was collected, exit without writing coverage information
>>
Warning: Task "mocha_istanbul:coverage" failed. Use --force to continue.

Aborted due to warnings.

**Comment by KimberlyMunoz** [comment]
Delete your node_modules folder and run npm install again.

**Comment by grapesmoker** [comment]
Just did that, still having same issue.

**Comment by KimberlyMunoz** [comment]
The node dependency issue that caused those errors is fixed in #700. Should be good after that.

**Comment by ascott1** [comment]
@grapesmoker Should we merge this and then @KimberlyMunoz or I can update the grunt instructions?

**Comment by grapesmoker** [comment]
I think we should just update the grunt instructions. My edit was based on
an erroneous understanding of what was going on.

On Fri, Mar 27, 2015 at 9:49 AM, Adam Scott <notifications@github.com>
wrote:

> @grapesmoker <https://github.com/grapesmoker> Should we merge this and
> then @KimberlyMunoz <https://github.com/KimberlyMunoz> or I can update
> the grunt instructions?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/cfpb/regulations-site/pull/699#issuecomment-86944914>.
>



-- 
http://www.google.com/profiles/grapesmoker

**Comment by ascott1** [comment]
Cool. Let's close this and I'll update those instructions.

**Pull request closed without merging**
