### PR TITLE
Reorganized some files in the head for performance issues

### PR DESCRIPTION
**Pull request by KimberlyMunoz**
Right now, we see this when we do a performance audit.

image

I changed the way our scripts and styles are ordered so that our inline script doesn't come between the styles and scripts. [Google has a great little video on it here](https://www.youtube.com/watch?v=AWF7ZzPyagE).

It's a small change, but hopefully has some noticeable effects on getting the page to render more quickly.

### CODE REVIEW

**Comment by ascott1** [comment]
@KimberlyMunoz have you tested this in IE8? Before merging I just want to make sure that moving the modernizr script doesn't have any consequences.

Thanks for doing this!

**Comment by KimberlyMunoz** [comment]
Good catch. I'll test this morning.

**Comment by KimberlyMunoz** [comment]
I didn't see any issues in IE8, but I think it's better to move it before the main javascript file since we do check for pushState support in Modernizr.

**Comment by ascott1** [comment]
:+1: that makes sense to me!

**Pull request merged**
