### PR TITLE
Remove old style analytics

### PR DESCRIPTION
**Pull request by ascott1**
We were given the go ahead to test out only using Google tag manager. This should greatly reduce the number of requests as we were sending data to three different analytics accounts.

This also makes sure that jQuery is globally accessible as both `jQuery` and `$` for our tag manager code.

### CODE REVIEW

**Comment by ascott1** [comment]
@mistergone can you give this a thumbs up before its merged?

**Comment by mistergone** [comment]
:+1: 

Sorry for the delay on this!

**Comment by ascott1** [comment]
No delay! I just pushed it recently. Thanks for the go ahead!

**Comment by mistergone** [comment]
Ah, my computer's date is somehow tomorrow, so everything says, "A day ago," because today is yesterday according to my computer. :rocket: :space_invader:

**Comment by KimberlyMunoz** [comment]
Should I test and merge?

**Comment by ascott1** [comment]
If you're up for it @KimberlyMunoz, I'd appreciate it!

**Comment by KimberlyMunoz** [comment]
Looks good. Thanks for trimming that, @ascott1! 💇🏽

**Pull request merged**
