### PR TITLE
WIP: Get satellite app tests working

### PR DESCRIPTION
**Pull request by hillaryj**
Renames all tests from `*_test(s).py` to `test_*.py` so the django test
runner will detect them.

### CODE REVIEW

**Comment by chosak** [comment]
@hillaryj I get [several errors](https://gist.github.com/chosak/9eefbc98534ef826fe22bc38cb4f3136) when running using this PR. Renaming to `test_*.py` does work (needed because cfgov-refresh doesn't use nose) but it looks like things aren't configured properly. Do all of the tests pass for you?

**Comment by hillaryj** [comment]
Oh! Yes, I wasn't clear - there are quite a few known errors when running the test from `cfgov-refresh`, but `python manage.py test` in `regulations-site` should have no errors.

From previous discussion of `regulations-core` testing, my aim was to get all the tests running locally in their repo with no errors. In this repo, I'd done the renaming but not far down the debugging path - should I continue with trying to get the tests to run as a satellite app in `cfgov-refresh`? Or, should we leave it (either with no changes or just file renaming) as part of the decision regarding past repos?

**Comment by chosak** [comment]
@hillaryj all of these tests already work for me in master with `python manage.py test`. The renaming isn't necessary in this repo because `regulations.settings.dev` (which is referred to in `manage.py`) uses a Nose-based test runner that doesn't require `test_*.py` filenames. Is this change really necessary if just for this repo alone?

As to your larger question I would defer to any discussion in GHE about plans for satellite app testing.

**Comment by hillaryj** [comment]
Nope, unnecessary at this point then.

**Pull request closed without merging**
