### PR TITLE
Add npm postinstall script

### PR DESCRIPTION
**Pull request by ascott1**
Now running `npm install` will also run `bower install` and the default `grunt` task, to simplify the front-end build process.

This also rids us of the pesky `.min.css` file, which was apparently hanging around somewhere.

### CODE REVIEW

**Comment by ascott1** [comment]
@KimberlyMunoz when you get a chance, can you review this and make sure it does what's advertised on the tin?

**Comment by KimberlyMunoz** [comment]
Yep. I'll get to this soon, especially if it means we're done with that .min.css file.

**Comment by ascott1** [comment]
:fire: `.min.css` :fire:

**Comment by KimberlyMunoz** [comment]
The postinstall script works great and I think that's ready to go. But I'm getting an error with JSDOM when I run the unit tests since it looks like they dropped support for 4.x on node.js
```
`jsdom 4.x onward only works on io.js, not Node.js™: https://github.com/tmpvar
```

Changing L30 of package.json to `"jsdom": "^3.1.2",` fixes it.

**Comment by ascott1** [comment]
Oh man, that is frustrating. I'll make that change and push.

**Comment by KimberlyMunoz** [comment]
Looks good! Merging ⚡️

**Comment by ascott1** [comment]
Thanks! :zap:

**Pull request merged**
